default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: tms_development

test: &test
  <<: *default
  database: tms_test

production:
  <<: *default
  database: tms_production

cucumber:
  <<: *test